// Central registry of ALL editable content keys on the website.
// The admin panel uses this as source of truth — fields appear even if no DB row exists yet.
//
// INVARIANT: every key in here is read by at least one rendered component, and every
// key read by a rendered component is in here. Drift between the two causes the dreaded
// "I edited a field in /admin and the page doesn't change" bug.
//
// Dynamic / structured content (case studies, testimonials, job posts, bank accounts,
// client logos) lives in dedicated Supabase tables with their own admin panels and is
// intentionally NOT registered here.

export interface ContentField {
  section: string;
  key: string;
  label: string;
  defaultValue: string;
  type?: "text" | "upload"; // "upload" renders a file-picker instead of a textarea
}

export const sectionOrder = [
  "seo",
  "nav",
  "hero",
  "stats",
  "about",
  "edges",
  "values",
  "founder",
  "clients",
  "testimonials",
  "tech",
  "google",
  "legal",
  "contact",
  "footer",
  "studios",
  "careers",
  "investors",
  "whatsapp",
  "odoo",
  "yanolja",
  "zoho",
];

export const sectionLabels: Record<string, string> = {
  seo:          "SEO & Meta Tags",
  nav:          "Navigation",
  hero:         "Homepage — Hero",
  stats:        "Homepage — Stats",
  about:        "Homepage — About",
  edges:        "Homepage — Why We're Different",
  values:       "Homepage — What We Stand For",
  founder:      "Homepage — Founder",
  clients:      "Homepage — Clients",
  testimonials: "Homepage — Testimonials",
  tech:         "Tech Stack (Teaser + Page)",
  google:       "Homepage — Google Business Card",
  legal:        "Homepage — Legal Strip",
  contact:      "Contact Section + Modal",
  footer:       "Footer",
  studios:      "Studios Page",
  careers:      "Careers Page",
  investors:    "Investors Page",
  whatsapp:     "WhatsApp Chat Widget",
  odoo:         "Odoo Partner Page",
  yanolja:      "Yanolja Partner Page",
  zoho:         "Zoho Partner Page",
};

export const contentRegistry: ContentField[] = [
  // ──────────────── SEO & Meta ────────────────
  { section: "seo", key: "seo_global_og_image",     label: "Global OG Image (1200×630, used when a page doesn't set its own)", defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_ga4_id",              label: "Google Analytics 4 Measurement ID (e.g. G-XXXXXXX)",               defaultValue: "" },
  { section: "seo", key: "seo_gsc_verification",    label: "Google Search Console Verification Code",                          defaultValue: "" },
  { section: "seo", key: "seo_home_title",          label: "Home — Title",                  defaultValue: "Dubai in Cairo — Digital Marketing & eBusiness Agency in Cairo, Egypt" },
  { section: "seo", key: "seo_home_description",    label: "Home — Description",            defaultValue: "Dubai in Cairo is Cairo's leading digital marketing and eBusiness solutions agency. We deliver data-driven growth, eCommerce, branding, and Odoo ERP across Egypt and the Middle East." },
  { section: "seo", key: "seo_home_og_image",       label: "Home — OG Image (overrides global)", defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_studios_title",       label: "Studios — Title",               defaultValue: "Our Studios — Dubai in Cairo" },
  { section: "seo", key: "seo_studios_description", label: "Studios — Description",         defaultValue: "Six specialized studios delivering integrated digital marketing, eCommerce, branding, and Odoo ERP across Egypt and the Middle East." },
  { section: "seo", key: "seo_tech_title",          label: "Tech Stack — Title",            defaultValue: "Tech Stack — Dubai in Cairo" },
  { section: "seo", key: "seo_tech_description",    label: "Tech Stack — Description",      defaultValue: "The 41 industry-leading tools we use to deliver growth, operations, and innovation for our clients." },
  { section: "seo", key: "seo_careers_title",       label: "Careers — Title",               defaultValue: "Careers at Dubai in Cairo" },
  { section: "seo", key: "seo_careers_description", label: "Careers — Description",         defaultValue: "Join Dubai in Cairo — a Cairo-based digital marketing and eBusiness agency hiring across strategy, creative, and technology." },
  { section: "seo", key: "seo_cases_title",         label: "Case Studies — Title",          defaultValue: "Case Studies — Dubai in Cairo" },
  { section: "seo", key: "seo_cases_description",   label: "Case Studies — Description",    defaultValue: "Real results from our work with brands across pharma, F&B, hospitality, government, and tech." },
  { section: "seo", key: "seo_odoo_title",          label: "Odoo Partner — Title",          defaultValue: "Odoo Partner — Dubai in Cairo" },
  { section: "seo", key: "seo_odoo_description",    label: "Odoo Partner — Description",    defaultValue: "Dubai in Cairo is a verified Odoo partner delivering integrated ERP, accounting, inventory, and commerce solutions for businesses in Egypt and the Middle East." },
  { section: "seo", key: "seo_yanolja_title",       label: "Yanolja Partner — Title",       defaultValue: "Yanolja Cloud Partnership — Dubai in Cairo" },
  { section: "seo", key: "seo_yanolja_description", label: "Yanolja Partner — Description", defaultValue: "Yanolja Cloud hospitality technology implementation by Dubai in Cairo — PMS, channel manager, booking engine, and POS for hotels and resorts across the region." },
  { section: "seo", key: "seo_zoho_title",          label: "Zoho Partner — Title",          defaultValue: "Zoho Enablement Experts — Dubai in Cairo" },
  { section: "seo", key: "seo_zoho_description",    label: "Zoho Partner — Description",    defaultValue: "Dubai in Cairo operationalizes the Zoho suite for businesses across Egypt and the Middle East — CRM, Books, Inventory, Desk, and more." },
  { section: "seo", key: "seo_faq_title",           label: "FAQ — Title",                   defaultValue: "FAQ — Dubai in Cairo" },
  { section: "seo", key: "seo_faq_description",     label: "FAQ — Description",             defaultValue: "Frequently asked questions about working with Dubai in Cairo — services, scope, timelines, and pricing." },
  { section: "seo", key: "seo_privacy_title",       label: "Privacy Policy — Title",        defaultValue: "Privacy Policy — Dubai in Cairo" },
  { section: "seo", key: "seo_privacy_description", label: "Privacy Policy — Description",  defaultValue: "How Dubai in Cairo handles personal data collected through our website and services." },

  // ──────────────── Navigation ────────────────
  { section: "nav", key: "nav_brand_1",           label: "Brand Wordmark — Part 1 (gold)",   defaultValue: "Dubai" },
  { section: "nav", key: "nav_brand_2",           label: "Brand Wordmark — Part 2 (white)",  defaultValue: "in" },
  { section: "nav", key: "nav_brand_3",           label: "Brand Wordmark — Part 3 (gold)",   defaultValue: "Cairo" },
  { section: "nav", key: "nav_favicon_url",       label: "Favicon URL",                      defaultValue: "/favicon.svg", type: "upload" },
  { section: "nav", key: "nav_link_home",         label: "Link — Home",                      defaultValue: "Home" },
  { section: "nav", key: "nav_link_services",     label: "Link — Services (dropdown)",       defaultValue: "Services" },
  { section: "nav", key: "nav_link_studios",      label: "Sub-link — Studios",               defaultValue: "Studios" },
  { section: "nav", key: "nav_link_tech",         label: "Sub-link — Technology",            defaultValue: "Technology" },
  { section: "nav", key: "nav_link_faq",          label: "Sub-link — FAQ",                   defaultValue: "FAQ" },
  { section: "nav", key: "nav_link_company",      label: "Link — Company (dropdown)",        defaultValue: "Company" },
  { section: "nav", key: "nav_link_careers",      label: "Sub-link — Careers",               defaultValue: "Careers" },
  { section: "nav", key: "nav_link_investors",    label: "Sub-link — Investors",             defaultValue: "Investors" },
  { section: "nav", key: "nav_link_partnerships", label: "Link — Partnerships (dropdown)",   defaultValue: "Partnerships" },
  { section: "nav", key: "nav_partner_odoo",      label: "Partnerships Menu — Odoo",         defaultValue: "Odoo ERP" },
  { section: "nav", key: "nav_partner_yanolja",   label: "Partnerships Menu — Yanolja",      defaultValue: "Yanolja Cloud" },
  { section: "nav", key: "nav_partner_zoho",      label: "Partnerships Menu — Zoho",         defaultValue: "Zoho" },
  { section: "nav", key: "nav_cta",               label: "Top-right CTA Button",             defaultValue: "Get Started" },

  // ──────────────── Homepage — Hero ────────────────
  { section: "hero", key: "hero_tagline",        label: "Eyebrow Tagline",                defaultValue: "Dubai's Quality · Cairo's Reach" },
  { section: "hero", key: "hero_headline",       label: "Main Headline",                  defaultValue: "Data-Powered Growth. Science-Fueled Success." },
  { section: "hero", key: "hero_subheadline",    label: "Subheadline / Body",             defaultValue: "We help ambitious businesses grow through the internet — with proven systems, measurable results, and a commitment to doing things differently." },
  { section: "hero", key: "hero_cta_primary",    label: "Primary CTA Label",              defaultValue: "Explore Our Services" },
  { section: "hero", key: "hero_cta_secondary",  label: "Secondary CTA Label",            defaultValue: "Talk to Our Team" },
  { section: "hero", key: "hero_card_label",     label: "Dashboard Card — Label",         defaultValue: "Growth Analytics" },
  { section: "hero", key: "hero_card_trend",     label: "Dashboard Card — Trend",         defaultValue: "+34% ↑" },
  { section: "hero", key: "hero_card_value",     label: "Dashboard Card — Value",         defaultValue: "216+" },
  { section: "hero", key: "hero_card_sublabel",  label: "Dashboard Card — Sub-label",     defaultValue: "Projects Delivered" },
  { section: "hero", key: "hero_float_1_value",  label: "Float Card 1 — Value",           defaultValue: "5.0 ★" },
  { section: "hero", key: "hero_float_1_label",  label: "Float Card 1 — Label",           defaultValue: "Google Rating" },
  { section: "hero", key: "hero_float_2_value",  label: "Float Card 2 — Value",           defaultValue: "50+" },
  { section: "hero", key: "hero_float_2_label",  label: "Float Card 2 — Label",           defaultValue: "Happy Clients" },
  { section: "hero", key: "hero_float_3_value",  label: "Float Card 3 — Value",           defaultValue: "5 Yrs" },
  { section: "hero", key: "hero_float_3_label",  label: "Float Card 3 — Label",           defaultValue: "In Business" },
  { section: "hero", key: "hero_float_4_value",  label: "Float Card 4 — Value",           defaultValue: "100%" },
  { section: "hero", key: "hero_float_4_label",  label: "Float Card 4 — Label",           defaultValue: "Digital-First" },

  // ──────────────── Homepage — Stats ────────────────
  { section: "stats", key: "stat_projects",       label: "Stat 1 — Value", defaultValue: "216" },
  { section: "stats", key: "stat_projects_label", label: "Stat 1 — Label", defaultValue: "Successful Projects" },
  { section: "stats", key: "stat_clients",        label: "Stat 2 — Value", defaultValue: "36+" },
  { section: "stats", key: "stat_clients_label",  label: "Stat 2 — Label", defaultValue: "Clients Served" },
  { section: "stats", key: "stat_years",          label: "Stat 3 — Value", defaultValue: "4+" },
  { section: "stats", key: "stat_years_label",    label: "Stat 3 — Label", defaultValue: "Years of Growth" },
  { section: "stats", key: "stat_digital",        label: "Stat 4 — Value", defaultValue: "100%" },
  { section: "stats", key: "stat_digital_label",  label: "Stat 4 — Label", defaultValue: "Digital Operation" },

  // ──────────────── Homepage — About ────────────────
  { section: "about", key: "about_subtitle",     label: "Eyebrow Text",                       defaultValue: "Who We Are" },
  { section: "about", key: "about_headline",     label: "Section Headline",                   defaultValue: "A Digital Agency Built on Science, Not Guesswork" },
  { section: "about", key: "about_body",         label: "Body Copy (rich text)",              defaultValue: "Founded in 2021, Dubai in Cairo is a Cairo-based digital marketing and eBusiness solutions agency." },
  { section: "about", key: "about_step_1_num",   label: "Step 1 — Number",                    defaultValue: "01" },
  { section: "about", key: "about_step_1_title", label: "Step 1 — Title",                     defaultValue: "Strategy & Research" },
  { section: "about", key: "about_step_1_desc",  label: "Step 1 — Description (rich text)",   defaultValue: "We start with data — auditing your market, competitors, and audience before writing a single line of copy or launching a single campaign." },
  { section: "about", key: "about_step_2_num",   label: "Step 2 — Number",                    defaultValue: "02" },
  { section: "about", key: "about_step_2_title", label: "Step 2 — Title",                     defaultValue: "Build & Execute" },
  { section: "about", key: "about_step_2_desc",  label: "Step 2 — Description (rich text)",   defaultValue: "Every channel, every creative, every system is built with precision — designed to work together as one growth engine, not isolated experiments." },
  { section: "about", key: "about_step_3_num",   label: "Step 3 — Number",                    defaultValue: "03" },
  { section: "about", key: "about_step_3_title", label: "Step 3 — Title",                     defaultValue: "Optimise & Scale" },
  { section: "about", key: "about_step_3_desc",  label: "Step 3 — Description (rich text)",   defaultValue: "Continuous testing, real-time analytics, and ruthless focus on what moves the needle. When something works, we scale it fast." },

  // ──────────────── Homepage — Why We're Different ────────────────
  { section: "edges", key: "edges_subtitle",  label: "Eyebrow Text",                          defaultValue: "Why We're Different" },
  { section: "edges", key: "edges_headline",  label: "Section Headline",                      defaultValue: "A Smarter Way to Grow Your Business Online" },
  { section: "edges", key: "edge_1_title",    label: "Card 1 — Title",                        defaultValue: "Intelligence-Powered Operations" },
  { section: "edges", key: "edge_1_desc",     label: "Card 1 — Description (rich text)",      defaultValue: "We leverage the latest AI tools and a rigorous electronic management system to streamline workflows. By combining emerging technology with automated tracking, we deliver high-quality projects faster and ensure that no detail ever slips through the cracks." },
  { section: "edges", key: "edge_2_title",    label: "Card 2 — Title",                        defaultValue: "Elite Global Expertise" },
  { section: "edges", key: "edge_2_desc",     label: "Card 2 — Description (rich text)",      defaultValue: "Our unique model connects you with a vetted network of more than 80 project-based specialists across the digital marketing and eCommerce fields. This flexible structure allows us to maintain expert-level quality while keeping costs lean, offering you high-tier talent without the traditional agency overhead." },
  { section: "edges", key: "edge_3_title",    label: "Card 3 — Title",                        defaultValue: "Performance-Based Value" },
  { section: "edges", key: "edge_3_desc",     label: "Card 3 — Description (rich text)",      defaultValue: "We believe in complete transparency, from our competitive pricing to our data-backed reporting. Every initiative is tied to clear KPIs and actionable insights, passing significant operational savings directly to you while ensuring you know exactly how your investment is driving growth." },

  // ──────────────── Homepage — What We Stand For ────────────────
  { section: "values", key: "values_subtitle", label: "Eyebrow Text",                          defaultValue: "What We Stand For" },
  { section: "values", key: "values_headline", label: "Section Headline",                      defaultValue: "Core beliefs shaping our approach" },
  { section: "values", key: "value_1_title",   label: "Value 1 — Title",                       defaultValue: "Clarity as a Foundation" },
  { section: "values", key: "value_1_desc",    label: "Value 1 — Description (rich text)",     defaultValue: "We believe impactful marketing is rooted in clear thinking and shared understanding. By championing open communication and continuous alignment on your core objectives, we ensure every strategy is built on a foundation of truth and transparency." },
  { section: "values", key: "value_2_title",   label: "Value 2 — Title",                       defaultValue: "Partners, Not Providers" },
  { section: "values", key: "value_2_desc",    label: "Value 2 — Description (rich text)",     defaultValue: "The most profound results emerge from genuine partnership, not transactional service delivery. Our philosophy is to integrate deeply with your vision. We don't just execute tasks; we take shared, personal responsibility for your sustained growth." },
  { section: "values", key: "value_3_title",   label: "Value 3 — Title",                       defaultValue: "Evolution Through Agility" },
  { section: "values", key: "value_3_desc",    label: "Value 3 — Description (rich text)",     defaultValue: "We believe sustainable growth demands a culture of testing, adapting, and embracing change. By valuing the agility to explore new channels and evolving market trends, we maintain the freedom to scale what works and intelligently refine what doesn't." },

  // ──────────────── Homepage — Founder ────────────────
  { section: "founder", key: "founder_subtitle",     label: "Eyebrow Text",                          defaultValue: "A Message from Our Founder" },
  { section: "founder", key: "founder_headline",     label: "Section Headline",                      defaultValue: "Built by Someone Who's Been in the Trenches." },
  { section: "founder", key: "founder_body",         label: "Body Copy (rich text)",                 defaultValue: "Elfouly founded Dubai'nCairo with a bold vision: a digital world teeming with opportunity and a belief that technology can fundamentally transform the way businesses operate and grow." },
  { section: "founder", key: "founder_name",         label: "Founder Name (used for portrait alt text)", defaultValue: "Abdalla Hassan Elfouly" },
  { section: "founder", key: "founder_photo_url",    label: "Founder Photo",                         defaultValue: "", type: "upload" },
  { section: "founder", key: "founder_quote",        label: "Quote Text (rich text)",                defaultValue: "I believe that continuous learning is the key to success in business. That's why I've completed 50+ specialized training courses in eBusiness, and I will never stop growing, nor will we." },
  { section: "founder", key: "founder_attribution",  label: "Quote Attribution",                     defaultValue: "— Abdalla Hassan Elfouly, CEO & Co-Founder" },
  { section: "founder", key: "founder_calendly_url", label: "Calendly Booking URL (shows the \"Reserve a Consultation\" CTA when set)", defaultValue: "" },
  { section: "founder", key: "founder_cta_label",    label: "CTA Button Label",                      defaultValue: "Reserve a Consultation" },
  { section: "founder", key: "founder_facebook",     label: "Facebook URL",                          defaultValue: "" },
  { section: "founder", key: "founder_linkedin",     label: "LinkedIn URL",                          defaultValue: "" },
  { section: "founder", key: "founder_instagram",    label: "Instagram URL",                         defaultValue: "" },

  // ──────────────── Homepage — Clients ────────────────
  // (Individual logos are managed in the dedicated "Client Logos" admin tab.)
  { section: "clients", key: "clients_subtitle",    label: "Eyebrow Text",     defaultValue: "Success Partners" },
  { section: "clients", key: "clients_headline",    label: "Section Headline", defaultValue: "Trusted by Brands That Mean Business" },
  { section: "clients", key: "clients_description", label: "Section Subtext",  defaultValue: "From global pharmaceutical giants to beloved local names." },

  // ──────────────── Homepage — Testimonials ────────────────
  // (Individual testimonials are managed in the dedicated "Testimonials" admin tab.)
  { section: "testimonials", key: "testimonials_subtitle", label: "Eyebrow Text",     defaultValue: "What Clients Say" },
  { section: "testimonials", key: "testimonials_headline", label: "Section Headline", defaultValue: "Trusted by Leaders.\nRecommended by Peers." },
  { section: "testimonials", key: "testimonials_subtext",  label: "Subtext",          defaultValue: "Real recommendations from clients and colleagues — pulled directly from LinkedIn." },

  // ──────────────── Tech Stack (Teaser on / and full /tech page) ────────────────
  { section: "tech", key: "tech_subtitle",         label: "Teaser — Eyebrow",          defaultValue: "Our Tech Stack" },
  { section: "tech", key: "tech_headline",         label: "Teaser — Headline",         defaultValue: "Integrated Solutions. Proven Tools." },
  { section: "tech", key: "tech_teaser_desc",      label: "Teaser — Description",      defaultValue: "41 industry-leading tools across 3 intelligent layers — purpose-built to drive growth, operations, and innovation." },
  { section: "tech", key: "tech_desc",             label: "Page — Section Subtext",    defaultValue: "Three intelligent layers — each purpose-built to cover a critical part of your business." },
  { section: "tech", key: "tech_page_headline",    label: "Page — Headline",           defaultValue: "The Technology Behind" },
  { section: "tech", key: "tech_page_subheadline", label: "Page — Subheadline",        defaultValue: "Every Result We Deliver" },
  { section: "tech", key: "tech_page_desc",        label: "Page — Intro Body",         defaultValue: "We don't just use tools — we architect intelligent stacks." },
  { section: "tech", key: "tech_cta_title",        label: "Page — CTA Title",          defaultValue: "Want to know which stack fits your business?" },
  { section: "tech", key: "tech_cta_desc",         label: "Page — CTA Body",           defaultValue: "We'll audit your current tools and recommend the right combination." },
  { section: "tech", key: "tech_cta_btn",          label: "Page — CTA Button",         defaultValue: "Get a Free Stack Audit" },

  // ──────────────── Homepage — Google Business Card ────────────────
  { section: "google", key: "google_biz_name",      label: "Business Name",                       defaultValue: "Dubai in Cairo" },
  { section: "google", key: "google_biz_category",  label: "Business Category",                   defaultValue: "Digital Marketing Agency" },
  { section: "google", key: "google_rating",        label: "Google Rating (e.g. 5.0)",            defaultValue: "5.0" },
  { section: "google", key: "google_address",       label: "Address",                             defaultValue: "100 Al-Mirghany St, Heliopolis, Cairo" },
  { section: "google", key: "google_maps_link",     label: "Google Maps Page URL (click target)", defaultValue: "https://maps.google.com" },
  { section: "google", key: "google_maps_embed",    label: "Google Maps Embed (full <iframe> snippet or src URL — if blank, falls back to the address above)", defaultValue: "" },
  { section: "google", key: "google_cta",           label: "CTA Button Label",                    defaultValue: "View on Google Maps" },

  // ──────────────── Homepage — Legal Strip ────────────────
  { section: "legal", key: "legal_subtitle",         label: "Eyebrow Text",       defaultValue: "Registered, Licensed & Ready to Operate" },
  { section: "legal", key: "legal_company_name",     label: "Company Legal Name", defaultValue: "Dubai in Cairo for Digital Marketing & eBusiness Solutions LLC" },
  { section: "legal", key: "legal_reg_label",        label: "Field 1 — Label",    defaultValue: "Commercial Registration" },
  { section: "legal", key: "legal_reg",              label: "Field 1 — Value",    defaultValue: "163772" },
  { section: "legal", key: "legal_membership_label", label: "Field 2 — Label",    defaultValue: "Chamber of IT & Telecom." },
  { section: "legal", key: "legal_membership",       label: "Field 2 — Value",    defaultValue: "4568" },
  { section: "legal", key: "legal_tax_label",        label: "Field 3 — Label",    defaultValue: "Tax Registration" },
  { section: "legal", key: "legal_tax",              label: "Field 3 — Value",    defaultValue: "625-626-168" },
  { section: "legal", key: "legal_sector_label",     label: "Field 4 — Label",    defaultValue: "Licensed Sector" },
  { section: "legal", key: "legal_sector",           label: "Field 4 — Value",    defaultValue: "eBusiness Solutions" },

  // ──────────────── Contact Section + Modal ────────────────
  { section: "contact", key: "contact_subtitle",            label: "Eyebrow Text",                            defaultValue: "Get Started" },
  { section: "contact", key: "contact_headline",            label: "Section Headline",                        defaultValue: "Ready to Grow?\nLet's Build." },
  { section: "contact", key: "contact_subtext",             label: "Section Subtext",                         defaultValue: "We're committed to delivering the best digital marketing and eCommerce services with measurable impact, flexible execution, and competitive pricing." },
  { section: "contact", key: "contact_trust_1",             label: "Trust Badge 1",                           defaultValue: "Response within 24 hours" },
  { section: "contact", key: "contact_trust_2",             label: "Trust Badge 2",                           defaultValue: "Free consultation call" },
  { section: "contact", key: "contact_trust_3",             label: "Trust Badge 3",                           defaultValue: "Transparent pricing" },
  { section: "contact", key: "contact_name_label",          label: "Form — Name Label",                       defaultValue: "Name *" },
  { section: "contact", key: "contact_name_placeholder",    label: "Form — Name Placeholder",                 defaultValue: "Your name" },
  { section: "contact", key: "contact_email_label",         label: "Form — Email Label",                      defaultValue: "Email *" },
  { section: "contact", key: "contact_email_placeholder",   label: "Form — Email Placeholder",                defaultValue: "you@company.com" },
  { section: "contact", key: "contact_phone_label",         label: "Form — Phone Label",                      defaultValue: "Phone *" },
  { section: "contact", key: "contact_phone_placeholder",   label: "Form — Phone Placeholder",                defaultValue: "100 000 0000" },
  { section: "contact", key: "contact_service_label",       label: "Form — Service Label",                    defaultValue: "Service of interest" },
  { section: "contact", key: "contact_message_label",       label: "Form — Message Label",                    defaultValue: "Message *" },
  { section: "contact", key: "contact_message_placeholder", label: "Form — Message Placeholder",              defaultValue: "Tell us about your project and goals..." },
  { section: "contact", key: "contact_cta",                 label: "Submit Button Label",                     defaultValue: "Start a Project" },
  { section: "contact", key: "contact_success_title",       label: "Success — Title",                         defaultValue: "Thank You!" },
  { section: "contact", key: "contact_success_msg",         label: "Success — Message",                       defaultValue: "We'll get back to you within 24 hours." },
  { section: "contact", key: "contact_success_btn",         label: "Success — Button Label",                  defaultValue: "Send Another Message" },
  { section: "contact", key: "contact_modal_title",         label: "Modal — Title (shown when nav \"Get Started\" opens the modal)", defaultValue: "Let's Build Together" },

  // ──────────────── Footer ────────────────
  { section: "footer", key: "footer_tagline",            label: "Tagline",            defaultValue: "From Dubai to Cairo, we transferred the scope, the challenges, and the quality." },
  { section: "footer", key: "footer_explore_label",      label: "Column Header — Explore",       defaultValue: "Explore" },
  { section: "footer", key: "footer_partnerships_label", label: "Column Header — Partnerships",  defaultValue: "Partnerships" },
  { section: "footer", key: "footer_phone_1",            label: "Phone 1",            defaultValue: "+20 120 200 0068" },
  { section: "footer", key: "footer_phone_2",            label: "Phone 2",            defaultValue: "+966 059 597 9064" },
  { section: "footer", key: "footer_copyright",          label: "Copyright",          defaultValue: "© 2025 Dubai in Cairo for Digital Marketing & eBusiness Solutions LLC · All Rights Reserved" },

  // ──────────────── Studios Page ────────────────
  { section: "studios", key: "studios_page_eyebrow",     label: "Page — Eyebrow",      defaultValue: "Our Studios" },
  { section: "studios", key: "studios_page_headline",    label: "Page — Headline",     defaultValue: "Six Specialized Studios." },
  { section: "studios", key: "studios_page_subheadline", label: "Page — Subheadline",  defaultValue: "One Unified Vision." },
  { section: "studios", key: "studios_page_desc",        label: "Page — Intro Body",   defaultValue: "Each studio is a focused center of excellence — handpicked specialists working in their native domain, all aligned behind a single goal: measurable growth for your business." },
  { section: "studios", key: "services_subtitle",        label: "Studios Grid — Eyebrow",  defaultValue: "Our Studios" },
  { section: "studios", key: "services_headline",        label: "Studios Grid — Headline", defaultValue: "Six Specialized Studios. One Unified Vision." },
  { section: "studios", key: "studios_cta_title",        label: "CTA — Title",         defaultValue: "Not sure which studio fits your goal?" },
  { section: "studios", key: "studios_cta_desc",         label: "CTA — Body",          defaultValue: "Tell us about your project and we'll match you with the right studio." },
  { section: "studios", key: "studios_cta_btn",          label: "CTA — Button Label",  defaultValue: "Start a Project" },
  { section: "studios", key: "studios_back_link",        label: "Back Link Label",     defaultValue: "Back to Home" },

  // ──────────────── Careers Page ────────────────
  { section: "careers", key: "careers_hero_badge",          label: "Hero — Badge",                          defaultValue: "We're Hiring" },
  { section: "careers", key: "careers_hero_headline_1",     label: "Hero — Headline (line 1)",              defaultValue: "Build the Future of" },
  { section: "careers", key: "careers_hero_headline_2",     label: "Hero — Headline (line 2 / accent)",     defaultValue: "Marketing with AI" },
  { section: "careers", key: "careers_hero_body",           label: "Hero — Body",                           defaultValue: "At Dubai in Cairo, we don't just deliver marketing solutions — we engineer growth using data, creativity, and AI-powered innovation." },
  { section: "careers", key: "careers_hero_pill_1",         label: "Hero — Pill 1",                         defaultValue: "✦ AUS Graduates Preferred" },
  { section: "careers", key: "careers_hero_pill_2",         label: "Hero — Pill 2",                         defaultValue: "✦ Gulf Experience Required" },
  { section: "careers", key: "careers_why_badge",           label: "Why DiC — Badge",                       defaultValue: "Why Dubai in Cairo" },
  { section: "careers", key: "careers_why_headline",        label: "Why DiC — Headline (line 1)",           defaultValue: "More Than a Job." },
  { section: "careers", key: "careers_why_headline_accent", label: "Why DiC — Headline (line 2 / accent)",  defaultValue: "A Career Accelerator." },
  { section: "careers", key: "careers_pref_title",          label: "Preferred — Title",                     defaultValue: "Preferred Qualifications" },
  { section: "careers", key: "careers_pref_1",              label: "Preferred — Item 1",                    defaultValue: "AUS graduates are preferred" },
  { section: "careers", key: "careers_pref_2",              label: "Preferred — Item 2",                    defaultValue: "Gulf experience is a must" },
  { section: "careers", key: "careers_jobs_badge",          label: "Open Roles — Badge",                    defaultValue: "Open Positions" },
  { section: "careers", key: "careers_jobs_headline",       label: "Open Roles — Headline",                 defaultValue: "Find Your Role" },
  { section: "careers", key: "careers_jobs_subtext",        label: "Open Roles — Subtext",                  defaultValue: "Click any position to view full details" },
  { section: "careers", key: "careers_apply_badge",         label: "How to Apply — Badge",                  defaultValue: "How to Apply" },
  { section: "careers", key: "careers_apply_headline",      label: "How to Apply — Headline",               defaultValue: "Ready to Join Us?" },
  { section: "careers", key: "careers_apply_body",          label: "How to Apply — Body",                   defaultValue: "Send your CV and portfolio (if applicable) to our careers inbox. Include the position title and your name in the subject line." },
  { section: "careers", key: "careers_apply_email",         label: "Careers Inbox Email",                   defaultValue: "careers@dubaicairo.com" },
  { section: "careers", key: "careers_apply_subject",       label: "Suggested Email Subject",               defaultValue: "[Position Title] – Your Name" },

  // ──────────────── Investors Page ────────────────
  { section: "investors", key: "investor_hero_badge",         label: "Hero — Badge",                          defaultValue: "Investor Relations" },
  { section: "investors", key: "investor_hero_headline_1",    label: "Hero — Headline (line 1)",              defaultValue: "Compounding Growth" },
  { section: "investors", key: "investor_hero_headline_2",    label: "Hero — Headline (line 2 / accent)",     defaultValue: "in MENA's Digital Economy" },
  { section: "investors", key: "investor_hero_body",          label: "Hero — Body (rich text)",               defaultValue: "We're building a profitable, AI-first digital growth studio serving ambitious businesses across the Middle East and North Africa. Five years of compounding revenue, a lean operating model, and a verified partner network across Odoo, Yanolja Cloud, and Zoho." },
  { section: "investors", key: "investor_hero_pill_1",        label: "Hero — Pill 1",                         defaultValue: "✦ MENA-Focused" },
  { section: "investors", key: "investor_hero_pill_2",        label: "Hero — Pill 2",                         defaultValue: "✦ Profitable Since 2022" },
  { section: "investors", key: "investor_hero_stat_1_value",  label: "Hero Stat 1 — Value",                   defaultValue: "+38%" },
  { section: "investors", key: "investor_hero_stat_1_label",  label: "Hero Stat 1 — Label",                   defaultValue: "YoY revenue growth" },
  { section: "investors", key: "investor_hero_stat_2_value",  label: "Hero Stat 2 — Value",                   defaultValue: "50+" },
  { section: "investors", key: "investor_hero_stat_2_label",  label: "Hero Stat 2 — Label",                   defaultValue: "Active clients" },
  { section: "investors", key: "investor_hero_stat_3_value",  label: "Hero Stat 3 — Value",                   defaultValue: "200+" },
  { section: "investors", key: "investor_hero_stat_3_label",  label: "Hero Stat 3 — Label",                   defaultValue: "Projects delivered" },
  { section: "investors", key: "investor_hero_stat_4_value",  label: "Hero Stat 4 — Value",                   defaultValue: "5" },
  { section: "investors", key: "investor_hero_stat_4_label",  label: "Hero Stat 4 — Label",                   defaultValue: "Years profitable" },
  { section: "investors", key: "investor_why_badge",          label: "Why Now — Badge",                       defaultValue: "Why Now" },
  { section: "investors", key: "investor_why_headline",       label: "Why Now — Headline",                    defaultValue: "A Defensible Position in an Underserved Region" },
  { section: "investors", key: "investor_why_1_title",        label: "Reason 1 — Title",                      defaultValue: "Market Tailwind" },
  { section: "investors", key: "investor_why_1_desc",         label: "Reason 1 — Description (rich text)",    defaultValue: "MENA digital ad spend is growing at double-digit rates while local execution capacity remains a fraction of demand — a structural gap we're built to close." },
  { section: "investors", key: "investor_why_2_title",        label: "Reason 2 — Title",                      defaultValue: "AI-First Operating Model" },
  { section: "investors", key: "investor_why_2_desc",         label: "Reason 2 — Description (rich text)",    defaultValue: "Our team operates with AI at every workflow, sustaining premium output at a lean cost base. Margins compound as we scale, not erode." },
  { section: "investors", key: "investor_why_3_title",        label: "Reason 3 — Title",                      defaultValue: "Compounding Track Record" },
  { section: "investors", key: "investor_why_3_desc",         label: "Reason 3 — Description (rich text)",    defaultValue: "Five consecutive profitable years, 50+ active clients, and verified partnerships across Odoo, Yanolja Cloud, and Zoho — the kind of foundation capital can accelerate." },
  { section: "investors", key: "investor_contact_badge",      label: "Contact — Badge",                       defaultValue: "Get in Touch" },
  { section: "investors", key: "investor_contact_headline",   label: "Contact — Headline",                    defaultValue: "Let's Talk Numbers" },
  { section: "investors", key: "investor_contact_body",       label: "Contact — Body (rich text)",            defaultValue: "We share full financials, growth metrics, and our roadmap with serious investors under NDA. Reach out and we'll schedule an introductory call within 48 hours." },
  { section: "investors", key: "investor_contact_email",      label: "Contact — Email",                       defaultValue: "investors@dubaiincairo.com" },
  { section: "investors", key: "seo_investors_title",         label: "SEO — Page Title",                      defaultValue: "Investor Relations · Dubai in Cairo" },
  { section: "investors", key: "seo_investors_description",   label: "SEO — Meta Description",                defaultValue: "Investor relations for Dubai in Cairo — a profitable AI-first digital growth studio serving the MENA region." },

  // ──────────────── WhatsApp Chat Widget ────────────────
  { section: "whatsapp", key: "wa_phone",            label: "Phone Number (digits only, no +)",   defaultValue: "201225250554" },
  { section: "whatsapp", key: "wa_teaser_title",     label: "Teaser Bubble — Title",              defaultValue: "👋 Hi! Let's start a conversation" },
  { section: "whatsapp", key: "wa_teaser_cta",       label: "Teaser Bubble — CTA",                defaultValue: "Tap to chat →" },
  { section: "whatsapp", key: "wa_header_name",      label: "Chat Header — Brand Name",           defaultValue: "Dubai in Cairo" },
  { section: "whatsapp", key: "wa_header_status",    label: "Chat Header — Status Line",          defaultValue: "Typically replies within 1 hour" },
  { section: "whatsapp", key: "wa_opener_text",      label: "Opening Message",                    defaultValue: "👋 Hi there! How can we help you today?" },
  { section: "whatsapp", key: "wa_opener_hint",      label: "Opening Message — Sub-hint",         defaultValue: "Pick one below" },
  { section: "whatsapp", key: "wa_reply_1_label",    label: "Quick Reply 1 — Button Label",       defaultValue: "I'd like to discuss a project" },
  { section: "whatsapp", key: "wa_reply_1_message",  label: "Quick Reply 1 — Sent Message",       defaultValue: "Hi! I'd like to discuss a project with your team." },
  { section: "whatsapp", key: "wa_reply_2_label",    label: "Quick Reply 2 — Button Label",       defaultValue: "I'd like a free consultation" },
  { section: "whatsapp", key: "wa_reply_2_message",  label: "Quick Reply 2 — Sent Message",       defaultValue: "Hi! I'd like to book a free 30-minute consultation." },
  { section: "whatsapp", key: "wa_reply_3_label",    label: "Quick Reply 3 — Button Label",       defaultValue: "I have a quick question" },
  { section: "whatsapp", key: "wa_reply_3_message",  label: "Quick Reply 3 — Sent Message",       defaultValue: "Hi! I have a question about your services." },
  { section: "whatsapp", key: "wa_reply_4_label",    label: "Quick Reply 4 — Button Label",       defaultValue: "I'm exploring a partnership" },
  { section: "whatsapp", key: "wa_reply_4_message",  label: "Quick Reply 4 — Sent Message",       defaultValue: "Hi! I'm interested in exploring a partnership with Dubai in Cairo." },
  { section: "whatsapp", key: "wa_footer_note",      label: "Footer Note",                        defaultValue: "Picks open WhatsApp with the message ready to send" },
  { section: "whatsapp", key: "wa_aria_open",        label: "Accessibility — Open Button Label",  defaultValue: "Open WhatsApp chat" },
  { section: "whatsapp", key: "wa_aria_close",       label: "Accessibility — Close Button Label", defaultValue: "Close WhatsApp chat" },
  { section: "whatsapp", key: "wa_aria_dismiss",     label: "Accessibility — Dismiss Teaser Label", defaultValue: "Dismiss" },

  // ──────────────── Odoo Partner Page ────────────────
  // Partnerships hero (shown above the Odoo content on /partnerships and /partnerships/odoo)
  { section: "odoo", key: "partnerships_badge",    label: "Partnerships Hero — Badge",    defaultValue: "Strategic Partnerships" },
  { section: "odoo", key: "partnerships_headline", label: "Partnerships Hero — Headline", defaultValue: "Our Technology Partners" },
  { section: "odoo", key: "partnerships_subtext",  label: "Partnerships Hero — Subtext",  defaultValue: "We have built deep implementation expertise across two technology ecosystems — Odoo for ERP and business automation, and Yanolja Cloud for hospitality management." },
  // Odoo content
  { section: "odoo", key: "odoo_page_badge",       label: "Page — Eyebrow Badge",       defaultValue: "ERP Partnership" },
  { section: "odoo", key: "odoo_page_headline",    label: "Page — Headline",            defaultValue: "Verified Odoo Partner" },
  { section: "odoo", key: "odoo_page_subtext",     label: "Page — Intro Body",          defaultValue: "We are a verified Odoo partner, enabling our clients to operate within a fully integrated ecosystem that connects eCommerce, digital marketing, and backend operations." },
  { section: "odoo", key: "odoo_partner_name",     label: "Partner Display Name",       defaultValue: "Odoo" },
  { section: "odoo", key: "odoo_logo_url",         label: "Odoo Logo",                  defaultValue: "", type: "upload" },
  { section: "odoo", key: "odoo_badge_label",      label: "Hero — Badge Label",         defaultValue: "Verified Partner" },
  { section: "odoo", key: "odoo_hero_badge",       label: "Hero — Eyebrow",             defaultValue: "ERP Partnership" },
  { section: "odoo", key: "odoo_hero_h1",          label: "Hero — Headline (start)",    defaultValue: "We are a" },
  { section: "odoo", key: "odoo_hero_h1_accent",   label: "Hero — Headline (accent)",   defaultValue: "Verified Odoo" },
  { section: "odoo", key: "odoo_hero_h1_end",      label: "Hero — Headline (end)",      defaultValue: "Partner" },
  { section: "odoo", key: "odoo_hero_body_1",      label: "Hero — Body Paragraph 1",    defaultValue: "We are now a verified Odoo partner, enabling our clients to consolidate all aspects of their business — from finance and inventory to CRM, HR, and project management — into one synchronized digital ecosystem." },
  { section: "odoo", key: "odoo_hero_body_2",      label: "Hero — Body Paragraph 2",    defaultValue: "That's why we've established a dedicated Odoo studio, specializing in scalable, on-premise, and customizable ERP solutions." },
  { section: "odoo", key: "odoo_suites_badge",     label: "Suites — Eyebrow Badge",     defaultValue: "Odoo Studio" },
  { section: "odoo", key: "odoo_suites_h2",        label: "Suites — Headline (line 1)", defaultValue: "Nine Integrated Suites." },
  { section: "odoo", key: "odoo_suites_h2_accent", label: "Suites — Headline (accent)", defaultValue: "One Unified Platform." },
  { section: "odoo", key: "odoo_cta_badge",        label: "CTA — Eyebrow Badge",        defaultValue: "Start the Conversation" },
  { section: "odoo", key: "odoo_cta_h2",           label: "CTA — Headline",             defaultValue: "Ready to Build Your Integrated Ecosystem?" },
  { section: "odoo", key: "odoo_cta_body",         label: "CTA — Body",                 defaultValue: "Let's connect your marketing engine to a fully synchronized ERP backbone." },
  { section: "odoo", key: "odoo_cta_btn",          label: "CTA — Button Label",         defaultValue: "Get in Touch" },

  // ──────────────── Yanolja Partner Page ────────────────
  { section: "yanolja", key: "yan_page_badge",        label: "Page — Eyebrow Badge",       defaultValue: "Hospitality Technology" },
  { section: "yanolja", key: "yan_page_headline",     label: "Page — Headline",            defaultValue: "Yanolja Cloud Partnership" },
  { section: "yanolja", key: "yan_page_subtext",      label: "Page — Intro Body",          defaultValue: "We have built extensive hands-on experience implementing Yanolja Cloud and its eZee suite across hospitality properties in Saudi Arabia." },
  { section: "yanolja", key: "yan_partner_name",      label: "Partner Display Name",       defaultValue: "Yanolja Cloud Solution" },
  { section: "yanolja", key: "yan_logo_url",          label: "Yanolja Logo",               defaultValue: "", type: "upload" },
  { section: "yanolja", key: "yan_badge_label",       label: "Hero — Badge Label",         defaultValue: "Specialized Implementor" },
  { section: "yanolja", key: "yan_hero_badge",        label: "Hero — Eyebrow",             defaultValue: "Hospitality Technology" },
  { section: "yanolja", key: "yan_hero_h2",           label: "Hero — Headline (start)",    defaultValue: "Yanolja Cloud" },
  { section: "yanolja", key: "yan_hero_h2_accent",    label: "Hero — Headline (accent)",   defaultValue: "Partnership" },
  { section: "yanolja", key: "yan_hero_body",         label: "Hero — Body (rich text)",    defaultValue: "We have also expanded our capabilities into the hospitality technology sector through our work with Yanolja Cloud and its suite of cloud-based management solutions. Over the past 12 months, we have built extensive hands-on experience implementing and integrating these systems across hospitality properties in Saudi Arabia, enabling fully digital, streamlined operations aligned with modern guest experiences. This practical exposure has positioned us as specialized implementors in hospitality tech, and we are now actively scaling these capabilities into new markets beyond Saudi Arabia." },
  { section: "yanolja", key: "yan_suites_badge",      label: "Suites — Eyebrow Badge",     defaultValue: "eZee Suite" },
  { section: "yanolja", key: "yan_suites_h2",         label: "Suites — Headline (line 1)", defaultValue: "Eight Integrated Solutions." },
  { section: "yanolja", key: "yan_suites_h2_accent",  label: "Suites — Headline (accent)", defaultValue: "One Hospitality Platform." },
  { section: "yanolja", key: "yan_cta_badge",         label: "CTA — Eyebrow Badge",        defaultValue: "Scale Your Hospitality Tech" },
  { section: "yanolja", key: "yan_cta_h2",            label: "CTA — Headline",             defaultValue: "Ready to Digitize Your Hospitality Operations?" },
  { section: "yanolja", key: "yan_cta_body",          label: "CTA — Body (rich text)",     defaultValue: "Our hospitality tech team brings 12 months of hands-on implementation experience across Saudi Arabia. Let's bring that expertise to your property." },
  { section: "yanolja", key: "yan_cta_btn",           label: "CTA — Button Label",         defaultValue: "Get in Touch" },

  // ──────────────── Zoho Partner Page ────────────────
  { section: "zoho", key: "zoho_page_badge",       label: "Page — Eyebrow Badge",       defaultValue: "Strategic Partnership" },
  { section: "zoho", key: "zoho_page_headline",    label: "Page — Headline",            defaultValue: "Zoho Enablement Experts" },
  { section: "zoho", key: "zoho_page_subtext",     label: "Page — Intro Body",          defaultValue: "We specialize in implementing Zoho applications and integrating them directly into your existing business and operational workflows." },
  { section: "zoho", key: "zoho_partner_name",     label: "Partner Display Name",       defaultValue: "Zoho" },
  { section: "zoho", key: "zoho_logo_url",         label: "Zoho Logo",                  defaultValue: "", type: "upload" },
  { section: "zoho", key: "zoho_badge_label",      label: "Hero — Badge Label",         defaultValue: "Enablement Expert" },
  { section: "zoho", key: "zoho_hero_badge",       label: "Hero — Eyebrow",             defaultValue: "CRM Partnership" },
  { section: "zoho", key: "zoho_hero_h1",          label: "Hero — Headline (start)",    defaultValue: "We are" },
  { section: "zoho", key: "zoho_hero_h1_accent",   label: "Hero — Headline (accent)",   defaultValue: "Zoho Enablement" },
  { section: "zoho", key: "zoho_hero_h1_end",      label: "Hero — Headline (end)",      defaultValue: "Experts" },
  { section: "zoho", key: "zoho_hero_body_1",      label: "Hero — Body Paragraph 1 (rich text)", defaultValue: "With over five years of hands-on experience, we help organizations deploy Zoho systems in a way that connects marketing, sales, and operations — ensuring that tools are not only installed, but fully adopted and operationalized." },
  { section: "zoho", key: "zoho_hero_body_2",      label: "Hero — Body Paragraph 2 (rich text)", defaultValue: "Our focus is on execution: configuring systems, aligning them with real business processes, and enabling teams to use them effectively to support day-to-day operations and growth activities." },
  { section: "zoho", key: "zoho_value_body",       label: "Value Body (rich text)",     defaultValue: "Zoho's value lies in how well it is implemented and integrated into actual workflows. We ensure that each application works within your business environment — from lead management and campaign execution to sales tracking and reporting — while providing the training needed for teams to operate independently and efficiently." },
  { section: "zoho", key: "zoho_suites_badge",     label: "Suites — Eyebrow Badge",     defaultValue: "Zoho Ecosystem" },
  { section: "zoho", key: "zoho_suites_h2",        label: "Suites — Headline (line 1)", defaultValue: "Six Integrated Suites." },
  { section: "zoho", key: "zoho_suites_h2_accent", label: "Suites — Headline (accent)", defaultValue: "One Unified Growth Engine." },
  { section: "zoho", key: "zoho_cta_badge",        label: "CTA — Eyebrow Badge",        defaultValue: "Start the Conversation" },
  { section: "zoho", key: "zoho_cta_h2",           label: "CTA — Headline",             defaultValue: "Ready to Operationalize Zoho for Your Business?" },
  { section: "zoho", key: "zoho_cta_body",         label: "CTA — Body (rich text)",     defaultValue: "Let's connect your Zoho environment to your actual business workflows. Our enablement team handles implementation, integration, and team training end to end." },
  { section: "zoho", key: "zoho_cta_btn",          label: "CTA — Button Label",         defaultValue: "Get in Touch" },
];
