// Central registry of ALL editable content keys on the website.
// The admin panel uses this as source of truth — fields appear even if not yet in DB.

export interface ContentField {
  section: string;
  key: string;
  label: string;
  defaultValue: string;
  type?: "text" | "upload"; // "upload" renders a file-picker instead of a textarea
}

export const sectionOrder = [
  "nav", "hero", "stats", "about", "edges", "values", "services", "studios",
  "founder", "clients", "testimonials", "tech", "google", "legal", "contact", "footer",
  "careers", "odoo", "yanolja", "zoho",
];

export const sectionLabels: Record<string, string> = {
  seo: "SEO & Meta Tags",
  nav: "Navigation",
  hero: "Hero Section",
  stats: "Statistics",
  about: "About Section",
  edges: "Why We're Different",
  values: "Our Values",
  services: "Studios — Grid Cards",
  studios: "Studios — Page Content",
  founder: "Founder Section",
  clients: "Clients Section",
  testimonials: "Testimonials",
  tech: "Tech Stack",
  google: "We're on Google",
  legal: "Legal & Registration",
  contact: "Contact Section",
  footer: "Footer",
  careers: "Careers Page",
  odoo: "Partnerships — Odoo",
  yanolja: "Partnerships — Yanolja Cloud",
  zoho: "Partnerships — Zoho",
};

export const contentRegistry: ContentField[] = [
  // ── SEO ──
  // Global
  { section: "seo", key: "seo_global_og_image",      label: "Global OG / Social Share Image (1200×630 px recommended)", defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_twitter_handle",       label: "Twitter / X Handle",          defaultValue: "@dubaiincairo" },
  { section: "seo", key: "seo_ga4_id",               label: "Google Analytics 4 — Measurement ID (e.g. G-XXXXXXXXXX)", defaultValue: "" },
  { section: "seo", key: "seo_gsc_verification",     label: "Google Search Console — Verification Code (content value only)", defaultValue: "" },
  // Per-page titles & descriptions
  { section: "seo", key: "seo_home_title",           label: "Home — Page Title",            defaultValue: "Dubai in Cairo | Strategy & Creative Agency" },
  { section: "seo", key: "seo_home_description",     label: "Home — Meta Description",      defaultValue: "Dubai in Cairo is a strategy and creative agency built for ambitious brands in Egypt and the Arab world." },
  { section: "seo", key: "seo_home_og_image",        label: "Home — OG Image (overrides global)", defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_studios_title",        label: "Studios — Page Title",         defaultValue: "Our Studios | Dubai in Cairo" },
  { section: "seo", key: "seo_studios_description",  label: "Studios — Meta Description",   defaultValue: "Explore Dubai in Cairo's creative and strategic studios — from branding and digital to events and performance marketing." },
  { section: "seo", key: "seo_studios_og_image",     label: "Studios — OG Image",          defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_careers_title",        label: "Careers — Page Title",         defaultValue: "Careers | Dubai in Cairo" },
  { section: "seo", key: "seo_careers_description",  label: "Careers — Meta Description",   defaultValue: "Join Dubai in Cairo. We're hiring strategists, creatives, and operators who want to build something real." },
  { section: "seo", key: "seo_careers_og_image",     label: "Careers — OG Image",          defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_contact_title",        label: "Contact — Page Title",         defaultValue: "Contact | Dubai in Cairo" },
  { section: "seo", key: "seo_contact_description",  label: "Contact — Meta Description",   defaultValue: "Get in touch with Dubai in Cairo. We work with brands across Egypt, the Gulf, and beyond." },
  { section: "seo", key: "seo_contact_og_image",     label: "Contact — OG Image",          defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_case_studies_title",   label: "Case Studies — Page Title",    defaultValue: "Case Studies | Dubai in Cairo" },
  { section: "seo", key: "seo_case_studies_description", label: "Case Studies — Meta Description", defaultValue: "Explore selected work from Dubai in Cairo — real campaigns, real results." },
  { section: "seo", key: "seo_case_studies_og_image",label: "Case Studies — OG Image",      defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_odoo_title",           label: "Odoo — Page Title",            defaultValue: "Odoo Partnership | Dubai in Cairo" },
  { section: "seo", key: "seo_odoo_description",     label: "Odoo — Meta Description",      defaultValue: "Dubai in Cairo is a certified Odoo partner — ERP, eCommerce, and marketing automation for Egypt and the Arab world." },
  { section: "seo", key: "seo_odoo_og_image",        label: "Odoo — OG Image",             defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_yanolja_title",        label: "Yanolja — Page Title",         defaultValue: "Yanolja Cloud Partnership | Dubai in Cairo" },
  { section: "seo", key: "seo_yanolja_description",  label: "Yanolja — Meta Description",   defaultValue: "Dubai in Cairo and Yanolja Cloud — hospitality tech and digital marketing for hotels and tourism brands." },
  { section: "seo", key: "seo_yanolja_og_image",     label: "Yanolja — OG Image",          defaultValue: "", type: "upload" },
  { section: "seo", key: "seo_zoho_title",           label: "Zoho — Page Title",            defaultValue: "Zoho Partnership | Dubai in Cairo" },
  { section: "seo", key: "seo_zoho_description",     label: "Zoho — Meta Description",      defaultValue: "Dubai in Cairo is a Zoho partner. CRM, marketing automation, and business intelligence for growth-focused brands." },
  { section: "seo", key: "seo_zoho_og_image",        label: "Zoho — OG Image",             defaultValue: "", type: "upload" },

  // ── Nav ──
  { section: "nav", key: "nav_brand",       label: "Brand name",       defaultValue: "Dubai in Cairo" },
  { section: "nav", key: "nav_link_1",      label: "Link 1",           defaultValue: "Work" },
  { section: "nav", key: "nav_link_2",      label: "Link 2",           defaultValue: "Studios" },
  { section: "nav", key: "nav_link_3",      label: "Link 3",           defaultValue: "About" },
  { section: "nav", key: "nav_link_4",      label: "Link 4",           defaultValue: "Careers" },
  { section: "nav", key: "nav_cta",         label: "CTA Button",       defaultValue: "Get in Touch" },
  { section: "nav", key: "nav_logo_url",    label: "Logo image URL (leave blank for text)", defaultValue: "", type: "upload" },

  // ── Hero ──
  { section: "hero", key: "hero_overline",    label: "Overline",       defaultValue: "The Cairo Agency Built for the Gulf" },
  { section: "hero", key: "hero_headline",    label: "Headline",       defaultValue: "We Don't Do Average" },
  { section: "hero", key: "hero_subheadline", label: "Sub-headline",   defaultValue: "Premium Strategy & Creative" },
  { section: "hero", key: "hero_body",        label: "Body copy",      defaultValue: "Dubai in Cairo blends Dubai's ambition with Cairo's creative energy — a strategy and creative agency for brands ready to lead." },
  { section: "hero", key: "hero_cta_primary",   label: "Primary CTA",  defaultValue: "Explore Our Studios" },
  { section: "hero", key: "hero_cta_secondary", label: "Secondary CTA",defaultValue: "See Our Work" },
  { section: "hero", key: "hero_chip_1",      label: "Chip 1",         defaultValue: "Cairo-based" },
  { section: "hero", key: "hero_chip_2",      label: "Chip 2",         defaultValue: "Gulf-focused" },
  { section: "hero", key: "hero_chip_3",      label: "Chip 3",         defaultValue: "Globally minded" },

  // ── Stats ──
  { section: "stats", key: "stat_years",          label: "Stat 1 Value",  defaultValue: "8+" },
  { section: "stats", key: "stat_years_label",    label: "Stat 1 Label",  defaultValue: "Years in Market" },
  { section: "stats", key: "stat_clients",        label: "Stat 2 Value",  defaultValue: "36+" },
  { section: "stats", key: "stat_clients_label",  label: "Stat 2 Label",  defaultValue: "Clients Served" },
  { section: "stats", key: "stat_industries",     label: "Stat 3 Value",  defaultValue: "12+" },
  { section: "stats", key: "stat_industries_label",label: "Stat 3 Label", defaultValue: "Industries" },
  { section: "stats", key: "stat_countries",      label: "Stat 4 Value",  defaultValue: "6" },
  { section: "stats", key: "stat_countries_label",label: "Stat 4 Label",  defaultValue: "Countries" },

  // ── About ──
  { section: "about", key: "about_subtitle",    label: "Section Subtitle",    defaultValue: "Who We Are" },
  { section: "about", key: "about_headline",    label: "Section Headline",    defaultValue: "Built at the Intersection of Ambition and Craft" },
  { section: "about", key: "about_description", label: "Section Description", defaultValue: "We are a strategy and creative agency that believes great work comes from genuine partnership. We embed ourselves in your business, understand your market, and deliver work that moves people — and numbers." },
  { section: "about", key: "about_cta",         label: "CTA Button",          defaultValue: "Our Story" },
  { section: "about", key: "about_metric_1_value", label: "Metric 1 — Value",   defaultValue: "95%" },
  { section: "about", key: "about_metric_1_label", label: "Metric 1 — Label",   defaultValue: "Client retention rate" },
  { section: "about", key: "about_metric_2_value", label: "Metric 2 — Value",   defaultValue: "3x" },
  { section: "about", key: "about_metric_2_label", label: "Metric 2 — Label",   defaultValue: "Average ROI delivered" },
  { section: "about", key: "about_metric_3_value", label: "Metric 3 — Value",   defaultValue: "48h" },
  { section: "about", key: "about_metric_3_label", label: "Metric 3 — Label",   defaultValue: "Average brief-to-concept" },

  // ── Edges ──
  { section: "edges", key: "edges_subtitle",     label: "Section Subtitle",    defaultValue: "Our Edge" },
  { section: "edges", key: "edges_headline",     label: "Section Headline",    defaultValue: "Why We're Different" },
  { section: "edges", key: "edges_description",  label: "Section Description", defaultValue: "We don't pitch decks and disappear. We partner, plan, and deliver — relentlessly." },
  { section: "edges", key: "edge_1_title",  label: "Edge 1 — Title",  defaultValue: "Hyper-Regional Expertise" },
  { section: "edges", key: "edge_1_desc",   label: "Edge 1 — Desc",   defaultValue: "We know the Egyptian and Gulf markets at a granular level — the audiences, the nuances, the channels that actually work." },
  { section: "edges", key: "edge_2_title",  label: "Edge 2 — Title",  defaultValue: "Full-Stack Creative" },
  { section: "edges", key: "edge_2_desc",   label: "Edge 2 — Desc",   defaultValue: "Strategy, creative, media, events, and production — all under one roof. No handoffs. No gaps." },
  { section: "edges", key: "edge_3_title",  label: "Edge 3 — Title",  defaultValue: "Results-Obsessed" },
  { section: "edges", key: "edge_3_desc",   label: "Edge 3 — Desc",   defaultValue: "We measure everything. Every campaign is tied to a business objective and tracked to the decimal." },
  { section: "edges", key: "edge_4_title",  label: "Edge 4 — Title",  defaultValue: "Senior Team, Always" },
  { section: "edges", key: "edge_4_desc",   label: "Edge 4 — Desc",   defaultValue: "You speak directly to the people doing the work. No account managers playing telephone." },

  // ── Values ──
  { section: "values", key: "values_subtitle",     label: "Section Subtitle",   defaultValue: "What Drives Us" },
  { section: "values", key: "values_headline",     label: "Section Headline",   defaultValue: "Our Core Values" },
  { section: "values", key: "values_description",  label: "Section Description",defaultValue: "The principles we work by, every project, every day." },
  { section: "values", key: "value_1_title", label: "Value 1 — Title", defaultValue: "Craft Over Comfort" },
  { section: "values", key: "value_1_desc",  label: "Value 1 — Desc",  defaultValue: "We push until the work is genuinely good — not just acceptable. Mediocrity is a choice we refuse to make." },
  { section: "values", key: "value_2_title", label: "Value 2 — Title", defaultValue: "Radical Transparency" },
  { section: "values", key: "value_2_desc",  label: "Value 2 — Desc",  defaultValue: "We tell clients what they need to hear, not what they want to hear. Trust is built on honesty, not flattery." },
  { section: "values", key: "value_3_title", label: "Value 3 — Title", defaultValue: "Ownership Mentality" },
  { section: "values", key: "value_3_desc",  label: "Value 3 — Desc",  defaultValue: "We treat every brand like it's our own. Your wins are our wins. Your problems are our problems." },

  // ── Services / Studios grid cards ──
  { section: "services", key: "services_subtitle",    label: "Section Subtitle",    defaultValue: "What We Do" },
  { section: "services", key: "services_headline",    label: "Section Headline",    defaultValue: "Six Studios. One Vision." },
  { section: "services", key: "services_description", label: "Section Description", defaultValue: "Each studio is a specialist unit. Together, they cover every dimension of modern brand building." },
  { section: "services", key: "studio_1_title", label: "Studio 1 — Title", defaultValue: "Strategy & Consulting" },
  { section: "services", key: "studio_1_desc",  label: "Studio 1 — Desc",  defaultValue: "Market entry, brand architecture, go-to-market strategy, and competitive positioning for regional and international brands." },
  { section: "services", key: "studio_2_title", label: "Studio 2 — Title", defaultValue: "Creative & Branding" },
  { section: "services", key: "studio_2_desc",  label: "Studio 2 — Desc",  defaultValue: "Brand identity, visual systems, campaigns, and content that makes people feel something." },
  { section: "services", key: "studio_3_title", label: "Studio 3 — Title", defaultValue: "Digital & Performance" },
  { section: "services", key: "studio_3_desc",  label: "Studio 3 — Desc",  defaultValue: "Paid media, SEO, social, and analytics built to drive real conversions — not vanity metrics." },
  { section: "services", key: "studio_4_title", label: "Studio 4 — Title", defaultValue: "Events & Experiential" },
  { section: "services", key: "studio_4_desc",  label: "Studio 4 — Desc",  defaultValue: "Corporate events, activations, and experiences that leave a mark — from concept to execution." },
  { section: "services", key: "studio_5_title", label: "Studio 5 — Title", defaultValue: "Production & Content" },
  { section: "services", key: "studio_5_desc",  label: "Studio 5 — Desc",  defaultValue: "Photography, video, motion graphics, and editorial content that performs across every platform." },
  { section: "services", key: "studio_6_title", label: "Studio 6 — Title", defaultValue: "Tech & Digital Products" },
  { section: "services", key: "studio_6_desc",  label: "Studio 6 — Desc",  defaultValue: "Websites, apps, and digital products engineered for scale, speed, and conversion." },

  // ── Studios page content ──
  { section: "studios", key: "studios_page_hero_overline",   label: "Hero Overline",    defaultValue: "Our Studios" },
  { section: "studios", key: "studios_page_hero_headline",   label: "Hero Headline",    defaultValue: "Six Studios.\nOne Unified Vision." },
  { section: "studios", key: "studios_page_hero_body",       label: "Hero Body",        defaultValue: "Each studio is a specialist unit — strategy, creative, digital, events, production, or tech. Together, they cover every dimension of modern brand building." },
  { section: "studios", key: "studios_page_cta",             label: "CTA Button",       defaultValue: "Get in Touch" },
  { section: "studios", key: "studios_page_studio_1_title",  label: "Studio 1 Title",   defaultValue: "Strategy & Consulting" },
  { section: "studios", key: "studios_page_studio_1_overline",label: "Studio 1 Overline",defaultValue: "Studio 01" },
  { section: "studios", key: "studios_page_studio_1_body",   label: "Studio 1 Body",    defaultValue: "We help brands understand where they stand, where they need to go, and how to get there. Our strategy studio combines deep market research, competitive intelligence, and senior-level consulting to build roadmaps that work in the real world." },
  { section: "studios", key: "studios_page_studio_1_tag_1", label: "Studio 1 — Tag 1", defaultValue: "Brand Architecture" },
  { section: "studios", key: "studios_page_studio_1_tag_2", label: "Studio 1 — Tag 2", defaultValue: "Market Entry" },
  { section: "studios", key: "studios_page_studio_1_tag_3", label: "Studio 1 — Tag 3", defaultValue: "GTM Strategy" },
  { section: "studios", key: "studios_page_studio_1_tag_4", label: "Studio 1 — Tag 4", defaultValue: "Positioning" },
  { section: "studios", key: "studios_page_studio_2_title",  label: "Studio 2 Title",   defaultValue: "Creative & Branding" },
  { section: "studios", key: "studios_page_studio_2_overline",label: "Studio 2 Overline",defaultValue: "Studio 02" },
  { section: "studios", key: "studios_page_studio_2_body",   label: "Studio 2 Body",    defaultValue: "Identity systems, campaign concepts, and content that earns attention. We build brands that people recognize, remember, and trust — from the logo to the language." },
  { section: "studios", key: "studios_page_studio_2_tag_1", label: "Studio 2 — Tag 1", defaultValue: "Brand Identity" },
  { section: "studios", key: "studios_page_studio_2_tag_2", label: "Studio 2 — Tag 2", defaultValue: "Visual Systems" },
  { section: "studios", key: "studios_page_studio_2_tag_3", label: "Studio 2 — Tag 3", defaultValue: "Campaign Creative" },
  { section: "studios", key: "studios_page_studio_2_tag_4", label: "Studio 2 — Tag 4", defaultValue: "Copywriting" },
  { section: "studios", key: "studios_page_studio_3_title",  label: "Studio 3 Title",   defaultValue: "Digital & Performance" },
  { section: "studios", key: "studios_page_studio_3_overline",label: "Studio 3 Overline",defaultValue: "Studio 03" },
  { section: "studios", key: "studios_page_studio_3_body",   label: "Studio 3 Body",    defaultValue: "Paid media, SEO, social strategy, and analytics that tie every spend to a result. We don't do vanity metrics — we do revenue." },
  { section: "studios", key: "studios_page_studio_3_tag_1", label: "Studio 3 — Tag 1", defaultValue: "Paid Social" },
  { section: "studios", key: "studios_page_studio_3_tag_2", label: "Studio 3 — Tag 2", defaultValue: "Google Ads" },
  { section: "studios", key: "studios_page_studio_3_tag_3", label: "Studio 3 — Tag 3", defaultValue: "SEO" },
  { section: "studios", key: "studios_page_studio_3_tag_4", label: "Studio 3 — Tag 4", defaultValue: "Analytics" },
  { section: "studios", key: "studios_page_studio_4_title",  label: "Studio 4 Title",   defaultValue: "Events & Experiential" },
  { section: "studios", key: "studios_page_studio_4_overline",label: "Studio 4 Overline",defaultValue: "Studio 04" },
  { section: "studios", key: "studios_page_studio_4_body",   label: "Studio 4 Body",    defaultValue: "From intimate brand activations to large-scale corporate events, we design experiences that people talk about long after they leave the room." },
  { section: "studios", key: "studios_page_studio_4_tag_1", label: "Studio 4 — Tag 1", defaultValue: "Corporate Events" },
  { section: "studios", key: "studios_page_studio_4_tag_2", label: "Studio 4 — Tag 2", defaultValue: "Brand Activations" },
  { section: "studios", key: "studios_page_studio_4_tag_3", label: "Studio 4 — Tag 3", defaultValue: "Conferences" },
  { section: "studios", key: "studios_page_studio_4_tag_4", label: "Studio 4 — Tag 4", defaultValue: "Experiential Design" },
  { section: "studios", key: "studios_page_studio_5_title",  label: "Studio 5 Title",   defaultValue: "Production & Content" },
  { section: "studios", key: "studios_page_studio_5_overline",label: "Studio 5 Overline",defaultValue: "Studio 05" },
  { section: "studios", key: "studios_page_studio_5_body",   label: "Studio 5 Body",    defaultValue: "Photo, video, motion, and editorial content built for every channel. We produce at the quality level you need — from social to cinema." },
  { section: "studios", key: "studios_page_studio_5_tag_1", label: "Studio 5 — Tag 1", defaultValue: "Photography" },
  { section: "studios", key: "studios_page_studio_5_tag_2", label: "Studio 5 — Tag 2", defaultValue: "Video Production" },
  { section: "studios", key: "studios_page_studio_5_tag_3", label: "Studio 5 — Tag 3", defaultValue: "Motion Graphics" },
  { section: "studios", key: "studios_page_studio_5_tag_4", label: "Studio 5 — Tag 4", defaultValue: "Content Strategy" },
  { section: "studios", key: "studios_page_studio_6_title",  label: "Studio 6 Title",   defaultValue: "Tech & Digital Products" },
  { section: "studios", key: "studios_page_studio_6_overline",label: "Studio 6 Overline",defaultValue: "Studio 06" },
  { section: "studios", key: "studios_page_studio_6_body",   label: "Studio 6 Body",    defaultValue: "Web, mobile, and custom digital products built for real scale. We engineer for speed, security, and conversion — not just aesthetics." },
  { section: "studios", key: "studios_page_studio_6_tag_1", label: "Studio 6 — Tag 1", defaultValue: "Web Development" },
  { section: "studios", key: "studios_page_studio_6_tag_2", label: "Studio 6 — Tag 2", defaultValue: "Mobile Apps" },
  { section: "studios", key: "studios_page_studio_6_tag_3", label: "Studio 6 — Tag 3", defaultValue: "E-commerce" },
  { section: "studios", key: "studios_page_studio_6_tag_4", label: "Studio 6 — Tag 4", defaultValue: "Automation" },

  // ── Founder ──
  { section: "founder", key: "founder_subtitle",      label: "Eyebrow Text",                          defaultValue: "A Message from Our Founder" },
  { section: "founder", key: "founder_headline",      label: "Section Headline",                      defaultValue: "Built by Someone Who's Been in the Trenches." },
  { section: "founder", key: "founder_body",          label: "Body Copy (rich text)",                 defaultValue: "Elfouly founded Dubai'nCairo with a bold vision: a digital world teeming with opportunity and a belief that technology can fundamentally transform the way businesses operate and grow." },
  { section: "founder", key: "founder_name",          label: "Founder Name (used for portrait alt)",  defaultValue: "Abdalla Hassan Elfouly" },
  { section: "founder", key: "founder_photo_url",     label: "Founder Photo",                          defaultValue: "", type: "upload" },
  { section: "founder", key: "founder_quote",         label: "Quote Text",                             defaultValue: "I believe that continuous learning is the key to success in business. That's why I've completed 50+ specialized training courses in eBusiness, and I will never stop growing, nor will we." },
  { section: "founder", key: "founder_attribution",   label: "Quote Attribution",                      defaultValue: "— Abdalla Hassan Elfouly, CEO & Co-Founder" },
  { section: "founder", key: "founder_calendly_url",  label: "Calendly Booking URL (shows the \"Reserve a Consultation\" CTA when set)", defaultValue: "" },
  { section: "founder", key: "founder_cta_label",     label: "CTA Button Label",                       defaultValue: "Reserve a Consultation" },
  { section: "founder", key: "founder_facebook",      label: "Facebook URL",                           defaultValue: "" },
  { section: "founder", key: "founder_linkedin",      label: "LinkedIn URL",                           defaultValue: "" },
  { section: "founder", key: "founder_instagram",     label: "Instagram URL",                          defaultValue: "" },

  // ── Clients ──
  { section: "clients", key: "clients_subtitle", label: "Section Subtitle", defaultValue: "Success Partners" },
  { section: "clients", key: "clients_headline", label: "Section Headline", defaultValue: "Trusted by Brands That Mean Business" },
  { section: "clients", key: "clients_description", label: "Section Description", defaultValue: "From global pharmaceutical giants to beloved local names." },
  // ── Client logo slots — leave a slot blank to skip it ───────────────────────
  // Tip: upload SVG or PNG with transparent background. The site automatically
  // converts every logo to a white monochrome silhouette so any brand colour
  // works. Slots without an uploaded file render the brand name as styled text.
  { section: "clients", key: "client_logo_1_enabled",  label: "Logo 1 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_1_name",     label: "Logo 1 — Brand Name (alt text)",  defaultValue: "Arma" },
  { section: "clients", key: "client_logo_1_url",      label: "Logo 1 — File (SVG or transparent PNG recommended)",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_2_enabled",  label: "Logo 2 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_2_name",     label: "Logo 2 — Brand Name (alt text)",  defaultValue: "Sanofi" },
  { section: "clients", key: "client_logo_2_url",      label: "Logo 2 — File",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_3_enabled",  label: "Logo 3 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_3_name",     label: "Logo 3 — Brand Name (alt text)",  defaultValue: "Novartis" },
  { section: "clients", key: "client_logo_3_url",      label: "Logo 3 — File",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_4_enabled",  label: "Logo 4 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_4_name",     label: "Logo 4 — Brand Name (alt text)",  defaultValue: "Roche" },
  { section: "clients", key: "client_logo_4_url",      label: "Logo 4 — File",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_5_enabled",  label: "Logo 5 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_5_name",     label: "Logo 5 — Brand Name (alt text)",  defaultValue: "Novo Nordisk" },
  { section: "clients", key: "client_logo_5_url",      label: "Logo 5 — File",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_6_enabled",  label: "Logo 6 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_6_name",     label: "Logo 6 — Brand Name (alt text)",  defaultValue: "Berlitz" },
  { section: "clients", key: "client_logo_6_url",      label: "Logo 6 — File",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_7_enabled",  label: "Logo 7 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_7_name",     label: "Logo 7 — Brand Name (alt text)",  defaultValue: "Monin" },
  { section: "clients", key: "client_logo_7_url",      label: "Logo 7 — File",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_8_enabled",  label: "Logo 8 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_8_name",     label: "Logo 8 — Brand Name (alt text)",  defaultValue: "Alpro" },
  { section: "clients", key: "client_logo_8_url",      label: "Logo 8 — File",   defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_9_enabled",  label: "Logo 9 — Enabled",  defaultValue: "true" },
  { section: "clients", key: "client_logo_9_name",     label: "Logo 9 — Brand Name (alt text)",  defaultValue: "Huawei" },
  { section: "clients", key: "client_logo_9_url",      label: "Logo 9 — File",   defaultValue: "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/huawei.svg", type: "upload" },
  { section: "clients", key: "client_logo_10_enabled", label: "Logo 10 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_10_name",    label: "Logo 10 — Brand Name (alt text)", defaultValue: "World Economic Forum" },
  { section: "clients", key: "client_logo_10_url",     label: "Logo 10 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_11_enabled", label: "Logo 11 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_11_name",    label: "Logo 11 — Brand Name (alt text)", defaultValue: "Banque Misr" },
  { section: "clients", key: "client_logo_11_url",     label: "Logo 11 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_12_enabled", label: "Logo 12 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_12_name",    label: "Logo 12 — Brand Name (alt text)", defaultValue: "The National Council for Women" },
  { section: "clients", key: "client_logo_12_url",     label: "Logo 12 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_13_enabled", label: "Logo 13 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_13_name",    label: "Logo 13 — Brand Name (alt text)", defaultValue: "ADCB Bank" },
  { section: "clients", key: "client_logo_13_url",     label: "Logo 13 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_14_enabled", label: "Logo 14 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_14_name",    label: "Logo 14 — Brand Name (alt text)", defaultValue: "Shark Tank Egypt" },
  { section: "clients", key: "client_logo_14_url",     label: "Logo 14 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_15_enabled", label: "Logo 15 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_15_name",    label: "Logo 15 — Brand Name (alt text)", defaultValue: "Sarj" },
  { section: "clients", key: "client_logo_15_url",     label: "Logo 15 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_16_enabled", label: "Logo 16 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_16_name",    label: "Logo 16 — Brand Name (alt text)", defaultValue: "EDGE Consultants" },
  { section: "clients", key: "client_logo_16_url",     label: "Logo 16 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_17_enabled", label: "Logo 17 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_17_name",    label: "Logo 17 — Brand Name (alt text)", defaultValue: "Abou Tarek" },
  { section: "clients", key: "client_logo_17_url",     label: "Logo 17 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_18_enabled", label: "Logo 18 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_18_name",    label: "Logo 18 — Brand Name (alt text)", defaultValue: "Quanta" },
  { section: "clients", key: "client_logo_18_url",     label: "Logo 18 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_19_enabled", label: "Logo 19 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_19_name",    label: "Logo 19 — Brand Name (alt text)", defaultValue: "San Benedetto" },
  { section: "clients", key: "client_logo_19_url",     label: "Logo 19 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_20_enabled", label: "Logo 20 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_20_name",    label: "Logo 20 — Brand Name (alt text)", defaultValue: "EduFun" },
  { section: "clients", key: "client_logo_20_url",     label: "Logo 20 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_21_enabled", label: "Logo 21 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_21_name",    label: "Logo 21 — Brand Name (alt text)", defaultValue: "El Kou5 Restaurant & Cafe" },
  { section: "clients", key: "client_logo_21_url",     label: "Logo 21 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_22_enabled", label: "Logo 22 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_22_name",    label: "Logo 22 — Brand Name (alt text)", defaultValue: "" },
  { section: "clients", key: "client_logo_22_url",     label: "Logo 22 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_23_enabled", label: "Logo 23 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_23_name",    label: "Logo 23 — Brand Name (alt text)", defaultValue: "" },
  { section: "clients", key: "client_logo_23_url",     label: "Logo 23 — File",  defaultValue: "", type: "upload" },
  { section: "clients", key: "client_logo_24_enabled", label: "Logo 24 — Enabled", defaultValue: "true" },
  { section: "clients", key: "client_logo_24_name",    label: "Logo 24 — Brand Name (alt text)", defaultValue: "" },
  { section: "clients", key: "client_logo_24_url",     label: "Logo 24 — File",  defaultValue: "", type: "upload" },

  // ── Testimonials — section header only (cards managed in Admin → Testimonials tab) ──
  { section: "testimonials", key: "testimonials_subtitle", label: "Section Subtitle", defaultValue: "What Clients Say" },
  { section: "testimonials", key: "testimonials_headline", label: "Section Headline", defaultValue: "Trusted by Leaders.\nRecommended by Peers." },
  { section: "testimonials", key: "testimonials_subtext",  label: "Section Subtext",  defaultValue: "Real recommendations from clients and colleagues — pulled directly from LinkedIn." },

  // ── Tech stack ──
  { section: "tech", key: "tech_subtitle",     label: "Section Subtitle",    defaultValue: "Our Stack" },
  { section: "tech", key: "tech_headline",     label: "Section Headline",    defaultValue: "Tools That Earn Their Place" },
  { section: "tech", key: "tech_description",  label: "Section Description", defaultValue: "We don't pick tools for clout. We pick them because they make the work better." },
  { section: "tech", key: "tech_category_1",   label: "Category 1",          defaultValue: "Strategy & Research" },
  { section: "tech", key: "tech_tools_1",      label: "Tools — Category 1",  defaultValue: "SEMrush · SimilarWeb · GWI · Statista · WARC" },
  { section: "tech", key: "tech_category_2",   label: "Category 2",          defaultValue: "Creative & Design" },
  { section: "tech", key: "tech_tools_2",      label: "Tools — Category 2",  defaultValue: "Adobe CC · Figma · Canva Pro · CapCut · Midjourney" },
  { section: "tech", key: "tech_category_3",   label: "Category 3",          defaultValue: "Paid Media & Analytics" },
  { section: "tech", key: "tech_tools_3",      label: "Tools — Category 3",  defaultValue: "Meta Ads · Google Ads · TikTok Ads · GA4 · Looker Studio" },
  { section: "tech", key: "tech_category_4",   label: "Category 4",          defaultValue: "CRM & Automation" },
  { section: "tech", key: "tech_tools_4",      label: "Tools — Category 4",  defaultValue: "HubSpot · Mailchimp · Zapier · Notion · Slack" },

  // ── Google Maps Widget ──
  { section: "google", key: "google_biz_name",     label: "Business Name",                                      defaultValue: "Dubai in Cairo" },
  { section: "google", key: "google_biz_category",  label: "Business Category",                                 defaultValue: "Digital Marketing Agency" },
  { section: "google", key: "google_rating",        label: "Google Rating (e.g. 4.9)",                          defaultValue: "5.0" },
  { section: "google", key: "google_address",       label: "Address (shown in the card)",                       defaultValue: "100 Al-Mirghany St, Heliopolis, Cairo" },
  { section: "google", key: "google_maps_link",     label: "Google Maps Page URL (click target)",               defaultValue: "" },
  { section: "google", key: "google_maps_embed",    label: "Google Maps Embed (optional — paste the full <iframe> snippet, or the src URL from Google Maps → Share → Embed a map. If left blank, the map renders from the Address above.)", defaultValue: "" },
  { section: "google", key: "google_cta",           label: "CTA Button Label",                                  defaultValue: "View on Google Maps" },

  // ── Legal strip (rendered as part of the Google Business widget — sits below the map row on /) ──
  { section: "legal", key: "legal_subtitle",         label: "Eyebrow Text",        defaultValue: "Registered, Licensed & Ready to Operate" },
  { section: "legal", key: "legal_company_name",     label: "Company Legal Name",  defaultValue: "Dubai in Cairo for Digital Marketing & eBusiness Solutions LLC" },
  { section: "legal", key: "legal_reg_label",        label: "Field 1 — Label",     defaultValue: "Commercial Registration" },
  { section: "legal", key: "legal_reg",              label: "Field 1 — Value",     defaultValue: "163772" },
  { section: "legal", key: "legal_membership_label", label: "Field 2 — Label",     defaultValue: "Chamber of IT & Telecom." },
  { section: "legal", key: "legal_membership",       label: "Field 2 — Value",     defaultValue: "4568" },
  { section: "legal", key: "legal_tax_label",        label: "Field 3 — Label",     defaultValue: "Tax Registration" },
  { section: "legal", key: "legal_tax",              label: "Field 3 — Value",     defaultValue: "625-626-168" },
  { section: "legal", key: "legal_sector_label",     label: "Field 4 — Label",     defaultValue: "Licensed Sector" },
  { section: "legal", key: "legal_sector",           label: "Field 4 — Value",     defaultValue: "eBusiness Solutions" },

  // ── Contact ──
  { section: "contact", key: "contact_subtitle",        label: "Section Subtitle",        defaultValue: "Get Started" },
  { section: "contact", key: "contact_headline",        label: "Section Headline",        defaultValue: "Ready to Grow?\nLet's Build." },
  { section: "contact", key: "contact_subtext",         label: "Section Subtext",         defaultValue: "We're committed to delivering the best digital marketing and eCommerce services with measurable impact, flexible execution, and competitive pricing." },
  { section: "contact", key: "contact_trust_1",         label: "Trust Signal 1",          defaultValue: "Response within 24 hours" },
  { section: "contact", key: "contact_trust_2",         label: "Trust Signal 2",          defaultValue: "Free consultation call" },
  { section: "contact", key: "contact_name_label",      label: "Name Field Label",        defaultValue: "Name *" },
  { section: "contact", key: "contact_name_placeholder",label: "Name Placeholder",        defaultValue: "Your name" },
  { section: "contact", key: "contact_email_label",     label: "Email Field Label",       defaultValue: "Email *" },
  { section: "contact", key: "contact_email_placeholder",label: "Email Placeholder",      defaultValue: "you@company.com" },
  { section: "contact", key: "contact_phone_label",     label: "Phone Field Label",       defaultValue: "Phone *" },
  { section: "contact", key: "contact_phone_placeholder",label: "Phone Placeholder",      defaultValue: "10 0000 0000" },
  { section: "contact", key: "contact_service_label",   label: "Service Chips Label",     defaultValue: "Service of interest" },
  { section: "contact", key: "contact_message_label",   label: "Message Field Label",     defaultValue: "Message *" },
  { section: "contact", key: "contact_message_placeholder",label: "Message Placeholder",  defaultValue: "Tell us about your project and goals..." },
  { section: "contact", key: "contact_cta",             label: "Submit Button Label",     defaultValue: "Start a Project" },
  { section: "contact", key: "contact_success_title",   label: "Success Title",           defaultValue: "Thank You!" },
  { section: "contact", key: "contact_success_msg",     label: "Success Message",         defaultValue: "We'll get back to you within 24 hours." },
  { section: "contact", key: "contact_success_btn",     label: "Success Button Label",    defaultValue: "Send Another Message" },

  // ── Footer ──
  { section: "footer", key: "footer_tagline",    label: "Tagline",             defaultValue: "Built for the Bold." },
  { section: "footer", key: "footer_copyright",  label: "Copyright Line",      defaultValue: "© 2025 Dubai in Cairo. All rights reserved." },
  { section: "footer", key: "footer_instagram",  label: "Instagram URL",       defaultValue: "" },
  { section: "footer", key: "footer_linkedin",   label: "LinkedIn URL",        defaultValue: "" },
  { section: "footer", key: "footer_facebook",   label: "Facebook URL",        defaultValue: "" },
  { section: "footer", key: "footer_tiktok",     label: "TikTok URL",          defaultValue: "" },

  // ── Careers page ──
  { section: "careers", key: "careers_hero_overline", label: "Hero Overline",  defaultValue: "Join Us" },
  { section: "careers", key: "careers_hero_headline", label: "Hero Headline",  defaultValue: "Work at Dubai in Cairo" },
  { section: "careers", key: "careers_hero_body",     label: "Hero Body",      defaultValue: "We're building a team of strategists, creatives, and operators who want to do the best work of their careers in the Arab world." },
  { section: "careers", key: "careers_perks_headline",label: "Perks Headline", defaultValue: "Why Join Us" },
  { section: "careers", key: "careers_perk_1",        label: "Perk 1",         defaultValue: "Senior clients, real budgets" },
  { section: "careers", key: "careers_perk_2",        label: "Perk 2",         defaultValue: "No corporate politics" },
  { section: "careers", key: "careers_perk_3",        label: "Perk 3",         defaultValue: "Hybrid and flexible" },
  { section: "careers", key: "careers_perk_4",        label: "Perk 4",         defaultValue: "Portfolio-building work" },
  { section: "careers", key: "careers_open_roles_headline", label: "Open Roles Headline", defaultValue: "Open Roles" },
  { section: "careers", key: "careers_no_roles_text", label: "No Open Roles Text", defaultValue: "No open roles right now — but we're always interested in exceptional people. Send your CV to careers@dubaiincairo.com" },

  // ── Odoo partnership page ──
  { section: "odoo", key: "odoo_page_header",    label: "Page Header",          defaultValue: "Partnerships" },
  { section: "odoo", key: "odoo_hero_overline",  label: "Hero Overline",        defaultValue: "Certified Odoo Partner" },
  { section: "odoo", key: "odoo_hero_headline",  label: "Hero Headline",        defaultValue: "Close the Loop Between Marketing and Operations" },
  { section: "odoo", key: "odoo_hero_body_1",   label: "Hero — Paragraph 1",        defaultValue: "We are now a verified Odoo partner, enabling our clients to operate within a fully integrated, closed-loop ecosystem that connects eCommerce, digital marketing, and backend operations. We believe that impactful marketing cannot exist in isolation — real, scalable results require a robust ERP system that digitally manages and synchronizes all operational processes." },
  { section: "odoo", key: "odoo_hero_body_2",   label: "Hero — Paragraph 2",        defaultValue: "As an Odoo partner, we bridge the gap between powerful technology and effective marketing. We don't just implement software; we architect complete business systems." },
  { section: "odoo", key: "odoo_logo_url",      label: "Odoo Logo",            defaultValue: "", type: "upload" },
  { section: "odoo", key: "odoo_service_1",     label: "Service Tag 1",        defaultValue: "Odoo ERP Implementation" },
  { section: "odoo", key: "odoo_service_2",     label: "Service Tag 2",        defaultValue: "eCommerce Integration" },
  { section: "odoo", key: "odoo_service_3",     label: "Service Tag 3",        defaultValue: "Marketing Automation" },
  { section: "odoo", key: "odoo_service_4",     label: "Service Tag 4",        defaultValue: "CRM Setup & Training" },
  { section: "odoo", key: "odoo_service_5",     label: "Service Tag 5",        defaultValue: "Inventory & Accounting" },
  { section: "odoo", key: "odoo_service_6",     label: "Service Tag 6",        defaultValue: "Custom Module Development" },
  { section: "odoo", key: "odoo_suite_1_title", label: "Suite 1 — Title",     defaultValue: "Sales & CRM" },
  { section: "odoo", key: "odoo_suite_1_body",  label: "Suite 1 — Body",      defaultValue: "Pipeline management, lead tracking, and sales automation that keeps your team focused on closing." },
  { section: "odoo", key: "odoo_suite_2_title", label: "Suite 2 — Title",     defaultValue: "Marketing Automation" },
  { section: "odoo", key: "odoo_suite_2_body",  label: "Suite 2 — Body",      defaultValue: "Email campaigns, social integrations, and lead nurturing sequences built directly into your ERP." },
  { section: "odoo", key: "odoo_suite_3_title", label: "Suite 3 — Title",     defaultValue: "eCommerce" },
  { section: "odoo", key: "odoo_suite_3_body",  label: "Suite 3 — Body",      defaultValue: "A native online store connected to your inventory, accounting, and fulfillment workflows." },
  { section: "odoo", key: "odoo_suite_4_title", label: "Suite 4 — Title",     defaultValue: "Inventory & Logistics" },
  { section: "odoo", key: "odoo_suite_4_body",  label: "Suite 4 — Body",      defaultValue: "Real-time stock visibility, multi-warehouse management, and automated reorder rules." },
  { section: "odoo", key: "odoo_suite_5_title", label: "Suite 5 — Title",     defaultValue: "Accounting & Finance" },
  { section: "odoo", key: "odoo_suite_5_body",  label: "Suite 5 — Body",      defaultValue: "Invoicing, expense tracking, bank reconciliation, and financial reporting — automated and audit-ready." },
  { section: "odoo", key: "odoo_suite_6_title", label: "Suite 6 — Title",     defaultValue: "HR & Payroll" },
  { section: "odoo", key: "odoo_suite_6_body",  label: "Suite 6 — Body",      defaultValue: "Employee records, leave management, payroll processing, and recruitment — all in one place." },
  { section: "odoo", key: "odoo_suite_7_title", label: "Suite 7 — Title",     defaultValue: "Project Management" },
  { section: "odoo", key: "odoo_suite_7_body",  label: "Suite 7 — Body",      defaultValue: "Tasks, milestones, timesheets, and billing — connected to your client and financial data." },
  { section: "odoo", key: "odoo_suite_8_title", label: "Suite 8 — Title",     defaultValue: "Manufacturing" },
  { section: "odoo", key: "odoo_suite_8_body",  label: "Suite 8 — Body",      defaultValue: "Production orders, BOMs, work centers, and quality control — for businesses that make things." },
  { section: "odoo", key: "odoo_suite_9_title", label: "Suite 9 — Title",     defaultValue: "Point of Sale" },
  { section: "odoo", key: "odoo_suite_9_body",  label: "Suite 9 — Body",      defaultValue: "In-store and online sales unified — with real-time inventory sync and customer loyalty features." },
  { section: "odoo", key: "odoo_cta_headline",  label: "CTA — Headline",      defaultValue: "Ready to Close the Loop?" },
  { section: "odoo", key: "odoo_cta_body",      label: "CTA — Body",          defaultValue: "Let's connect your Odoo environment to your actual business workflows. Our implementation team handles setup, migration, and training end to end." },
  { section: "odoo", key: "odoo_cta_btn",       label: "CTA — Button",        defaultValue: "Get in Touch" },

  // ── Yanolja Cloud partnership page ──
  { section: "yanolja", key: "yanolja_page_header",    label: "Page Header",       defaultValue: "Partnerships" },
  { section: "yanolja", key: "yanolja_hero_overline",  label: "Hero Overline",     defaultValue: "Yanolja Cloud Partner" },
  { section: "yanolja", key: "yanolja_hero_headline",  label: "Hero Headline",     defaultValue: "Hospitality Tech Meets Regional Marketing" },
  { section: "yanolja", key: "yanolja_hero_body",      label: "Hero Body",         defaultValue: "Dubai in Cairo is an official Yanolja Cloud partner for Egypt and the Arab world. We bring together Yanolja's enterprise-grade hospitality technology with our regional marketing and digital expertise." },
  { section: "yanolja", key: "yanolja_partner_name",  label: "Partner Name",      defaultValue: "Yanolja Cloud" },
  { section: "yanolja", key: "yanolja_logo_url",      label: "Yanolja Logo",      defaultValue: "", type: "upload" },
  { section: "yanolja", key: "yanolja_service_1",     label: "Service Tag 1",     defaultValue: "PMS Implementation" },
  { section: "yanolja", key: "yanolja_service_2",     label: "Service Tag 2",     defaultValue: "Channel Management" },
  { section: "yanolja", key: "yanolja_service_3",     label: "Service Tag 3",     defaultValue: "Revenue Optimization" },
  { section: "yanolja", key: "yanolja_service_4",     label: "Service Tag 4",     defaultValue: "Digital Marketing" },
  { section: "yanolja", key: "yanolja_service_5",     label: "Service Tag 5",     defaultValue: "OTA Strategy" },
  { section: "yanolja", key: "yanolja_service_6",     label: "Service Tag 6",     defaultValue: "Staff Training" },
  { section: "yanolja", key: "yanolja_product_1_title",label: "Product 1 — Title", defaultValue: "Property Management System" },
  { section: "yanolja", key: "yanolja_product_1_body", label: "Product 1 — Body",  defaultValue: "Cloud-based PMS for front desk, reservations, housekeeping, and reporting — built for hotels of every size." },
  { section: "yanolja", key: "yanolja_product_2_title",label: "Product 2 — Title", defaultValue: "Channel Manager" },
  { section: "yanolja", key: "yanolja_product_2_body", label: "Product 2 — Body",  defaultValue: "Sync rates and availability across Booking.com, Expedia, Airbnb, and 100+ OTAs in real time." },
  { section: "yanolja", key: "yanolja_product_3_title",label: "Product 3 — Title", defaultValue: "Booking Engine" },
  { section: "yanolja", key: "yanolja_product_3_body", label: "Product 3 — Body",  defaultValue: "Commission-free direct bookings from your own website, with dynamic pricing and upsell tools built in." },
  { section: "yanolja", key: "yanolja_product_4_title",label: "Product 4 — Title", defaultValue: "Revenue Management" },
  { section: "yanolja", key: "yanolja_product_4_body", label: "Product 4 — Body",  defaultValue: "Data-driven pricing recommendations to maximize ADR and occupancy across every season." },
  { section: "yanolja", key: "yanolja_product_5_title",label: "Product 5 — Title", defaultValue: "Guest Experience Platform" },
  { section: "yanolja", key: "yanolja_product_5_body", label: "Product 5 — Body",  defaultValue: "Pre-arrival communication, in-stay messaging, and post-stay feedback — all automated." },
  { section: "yanolja", key: "yanolja_product_6_title",label: "Product 6 — Title", defaultValue: "Analytics & Reporting" },
  { section: "yanolja", key: "yanolja_product_6_body", label: "Product 6 — Body",  defaultValue: "Real-time dashboards for occupancy, revenue, and guest sentiment — with benchmarking against comp set." },
  { section: "yanolja", key: "yanolja_product_7_title",label: "Product 7 — Title", defaultValue: "Housekeeping & Maintenance" },
  { section: "yanolja", key: "yanolja_product_7_body", label: "Product 7 — Body",  defaultValue: "Mobile task management, room status updates, and preventive maintenance scheduling for operations teams." },
  { section: "yanolja", key: "yanolja_product_8_title",label: "Product 8 — Title", defaultValue: "F&B & POS" },
  { section: "yanolja", key: "yanolja_product_8_body", label: "Product 8 — Body",  defaultValue: "Integrated point-of-sale and F&B management connected to the PMS for unified billing and inventory." },
  { section: "yanolja", key: "yanolja_cta_headline",  label: "CTA — Headline",    defaultValue: "Upgrade Your Property's Technology" },
  { section: "yanolja", key: "yanolja_cta_body",      label: "CTA — Body",        defaultValue: "Whether you're a boutique hotel or a large resort, we'll help you select, implement, and get the most out of Yanolja Cloud's hospitality platform." },
  { section: "yanolja", key: "yanolja_cta_btn",       label: "CTA — Button",      defaultValue: "Get in Touch" },

  // ── Zoho partnership page ──
  { section: "zoho", key: "zoho_page_header",    label: "Page Header",         defaultValue: "Partnerships" },
  { section: "zoho", key: "zoho_hero_overline",  label: "Hero Overline",       defaultValue: "Zoho Partner" },
  { section: "zoho", key: "zoho_hero_headline",  label: "Hero Headline",       defaultValue: "CRM, Automation, and Business Intelligence — Unified" },
  { section: "zoho", key: "zoho_hero_body",      label: "Hero Body",           defaultValue: "Dubai in Cairo is an official Zoho partner for Egypt and the Arab world. We implement, customize, and integrate Zoho's full suite of business applications to help growing companies operate smarter." },
  { section: "zoho", key: "zoho_logo_url",      label: "Zoho Logo",           defaultValue: "", type: "upload" },
  { section: "zoho", key: "zoho_service_1",     label: "Service Tag 1",       defaultValue: "Zoho CRM" },
  { section: "zoho", key: "zoho_service_2",     label: "Service Tag 2",       defaultValue: "Zoho Marketing Automation" },
  { section: "zoho", key: "zoho_service_3",     label: "Service Tag 3",       defaultValue: "Zoho Analytics" },
  { section: "zoho", key: "zoho_service_4",     label: "Service Tag 4",       defaultValue: "Zoho One Implementation" },
  { section: "zoho", key: "zoho_service_5",     label: "Service Tag 5",       defaultValue: "Custom Integrations" },
  { section: "zoho", key: "zoho_service_6",     label: "Service Tag 6",       defaultValue: "Team Training" },
  { section: "zoho", key: "zoho_suite_1_title", label: "Suite 1 — Title",    defaultValue: "Zoho CRM" },
  { section: "zoho", key: "zoho_suite_1_body",  label: "Suite 1 — Body",     defaultValue: "Lead management, deal tracking, and sales automation tailored to your pipeline and team structure." },
  { section: "zoho", key: "zoho_suite_2_title", label: "Suite 2 — Title",    defaultValue: "Zoho Campaigns" },
  { section: "zoho", key: "zoho_suite_2_body",  label: "Suite 2 — Body",     defaultValue: "Email marketing, automation workflows, and audience segmentation integrated with your CRM data." },
  { section: "zoho", key: "zoho_suite_3_title", label: "Suite 3 — Title",    defaultValue: "Zoho Analytics" },
  { section: "zoho", key: "zoho_suite_3_body",  label: "Suite 3 — Body",     defaultValue: "Custom dashboards and reports that pull from every Zoho app and external data source — in real time." },
  { section: "zoho", key: "zoho_suite_4_title", label: "Suite 4 — Title",    defaultValue: "Zoho Desk" },
  { section: "zoho", key: "zoho_suite_4_body",  label: "Suite 4 — Body",     defaultValue: "Customer support ticketing with SLA management, omnichannel inbox, and self-service portal." },
  { section: "zoho", key: "zoho_suite_5_title", label: "Suite 5 — Title",    defaultValue: "Zoho Projects" },
  { section: "zoho", key: "zoho_suite_5_body",  label: "Suite 5 — Body",     defaultValue: "Task management, Gantt charts, time tracking, and resource allocation for teams of any size." },
  { section: "zoho", key: "zoho_suite_6_title", label: "Suite 6 — Title",    defaultValue: "Zoho One" },
  { section: "zoho", key: "zoho_suite_6_body",  label: "Suite 6 — Body",     defaultValue: "The entire Zoho ecosystem in a single license — over 45 apps, unified data, and one login." },
  { section: "zoho", key: "zoho_cta_headline",  label: "CTA — Headline",     defaultValue: "Ready to Run on Zoho?" },
  { section: "zoho", key: "zoho_cta_body",      label: "CTA — Body",         defaultValue: "Let's connect your Zoho environment to your actual business workflows. Our enablement team handles implementation, integration, and team training end to end." },
  { section: "zoho", key: "zoho_cta_btn",       label: "CTA — Button",       defaultValue: "Get in Touch" },
];
